services:
  server:
    container_name: server
    depends_on:
      - db
    build: .
    ports:
      - '80:80'
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules

  db:
    container_name: db
    image: mysql:8.0.35
    restart: unless-stopped
    ports:
      - '3307:3306'
    env_file:
      - ./.env
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/dump:/docker-entrypoint-initdb.d

volumes:
  db-data:
    driver: local
    driver_opts:
      device: ./docker/db/data
  node_modules: